#! usr/bin/env python3

#Lexi Rossow
#M5 Practice Exercise
#Unique Password

from random import choice, sample 
num_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
alpha_list = ['c', 'd', 'f', 'g', 'h']
symbol_list = ['!', '@', '#', '$', '%']

password = []
for i in range(4):
    password.append(choice(num_list))
    password.append(choice(alpha_list))
    password.append(choice(symbol_list))

print("My new password is: ", password)
